version: '3.0'

expectations:
  population_size: 10000

actions:

  # Extract cohort for indicator HYP001 by month 
  generate_study_population_hyp001:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_hyp001 
      --index-date-range "2019-01-01 to 2022-01-01 by month" 
      --output-dir=output  
      --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_hyp001_*.feather

  #  Generate measures for indicator HYP001 by month
  generate_measures_hyp001:
      run: >
        cohortextractor:latest generate_measures 
        --study-definition study_definition_hyp001 
        --output-dir=output
      needs: [generate_study_population_hyp001]
      outputs:
        moderately_sensitive:
          measure_csv: output/measure_hyp001_*_rate.csv