version: '3.0'

expectations:
  population_size: 10000

actions:

  # Extract cohort for indicator HYP001 by month 
  generate_study_population_hyp001:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_hyp001 
      --index-date-range "2019-01-01 to 2022-01-01 by month" 
      --output-dir=output  
      --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_hyp001_*.feather

  #  Generate measures for indicator HYP001 by month
  generate_measures_hyp001:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_hyp001 
       --output-dir=output
     needs: [generate_study_population_hyp001]
     outputs:
       moderately_sensitive:
         measure_csv: output/measure_hyp001_*_rate.csv   
 
  # Extract cohort for indicator HYP003 by month 
  generate_study_population_hyp003:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_hyp003 
      --index-date-range "2019-01-01 to 2022-01-01 by month" 
      --output-dir=output  
      --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_hyp003_*.feather

  #  Generate measures for indicator HYP003 by month
  generate_measures_hyp003:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_hyp003 
       --output-dir=output
     needs: [generate_study_population_hyp003]
     outputs:
       moderately_sensitive:
         measure_csv: output/measure_hyp003_*_rate.csv  

  # Extract cohort for indicator HYP007 by month 
  generate_study_population_hyp007:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_hyp007 
      --index-date-range "2019-01-01 to 2022-01-01 by month" 
      --output-dir=output  
      --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_hyp007_*.feather

  #  Generate measures for indicator HYP007 by month
  generate_measures_hyp007:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_hyp007 
       --output-dir=output
     needs: [generate_study_population_hyp007]
     outputs:
       moderately_sensitive:
         measure_csv: output/measure_hyp007_*_rate.csv
