# Load packages and functions

```{r}
library(tidyverse)
library(lubridate)
library(here)
library(scales)
library(janitor)
library(patchwork)
library(gt)
```


```{r}
# Load plotting function
source(here::here("lib", "functions", "funs_plot_measures.R"))
source(here::here("lib", "functions", "funs_report_results.R"))
```

# Load data

```{r}

df_measures_bp_hyp <- read_csv(here("released_outputs/measures/df_measures_bp_hyp.csv")) |>
  mutate(indicator = factor(indicator,
    levels = c("hyp001", "hyp003", "hyp007", "bp002"),
    labels = c("HYP001 (Total population)", "HYP003 (Age <= 79)", "HYP007 (Age >= 80)", "BP002 (Age >= 45)")
  ))

# Change age band group for BP002 so plot legends can be combined
df_measures_bp_hyp <- df_measures_bp_hyp |>
  mutate(category = case_when(
    indicator == "BP002 (Age >= 45)" & group == "age_band" & category == "45-49" ~ "40-49",
    TRUE ~ category
  ))

df_measures_bp_hyp
```

# Results

```{r}

df_measures_bp_hyp |>
  filter(group == "population") |>
  filter(variable == "pct") |>
  group_by(indicator) |>
  summarise(
    min = min(value, na.rm = T),
    max = max(value, na.rm = T)
  )

df_measures_bp_hyp |>
  filter(group == "population") |>
  filter(variable == "pct") |>
  group_by(indicator) |>
  slice_min(order_by = value)

df_measures_bp_hyp |>
  filter(group == "population") |>
  filter(variable == "pct") |>
  group_by(indicator) |>
  slice_max(order_by = value)
```


```{r}

df_tab_fy2122 <- df_measures_bp_hyp |>
  mutate(indicator = factor(indicator,
    levels = c("HYP001 (Total population)", "HYP003 (Age <= 79)", "HYP007 (Age >= 80)", "BP002 (Age >= 45)"),
    labels = c("hyp001", "hyp003", "hyp007", "bp002")
  )) |>
  mutate(variable = case_when(
    indicator == "hyp001" & variable == "register" ~ "numerator",
    indicator == "hyp001" & variable == "population" ~ "denominator",
    TRUE ~ variable
  )) |>
  filter(variable %in% c("numerator", "denominator", "pct")) |>
  filter(date == "2022-03-01") |>
  mutate(value = na_if(value, 0)) |>
  filter(month(date) == 3) |>
  mutate(category = case_when(
    group == "population" ~ "",
    is.na(category) ~ "Unknown",
    TRUE ~ category
  )) |>
  arrange(indicator) |>
  mutate(date = paste0("fy", str_sub(year(date) - 1, -2, -1), str_sub(year(date), -2, -1))) |>
  pivot_wider(
    id_cols = c(group, category),
    names_from = c(indicator, date, variable),
    values_from = c(value)
  ) |>
  mutate(
    group = factor(group,
      levels = c("population", "sex", "age_band", "ethnicity", "imd_q5", "region", "care_home", "learning_disability"),
      labels = c("Population", "Sex", "Age band", "Ethnicity", "IMD", "Region", "Care home status", "Record or learning disability")
    ),
    category = case_when(
      category == "No record of care home status" ~ "No",
      category == "Record of care home status" ~ "Yes",
      category == "No record of learning disability" ~ "No",
      category == "Record of learning disability" ~ "Yes",
      TRUE ~ category
    )
  ) |>
  arrange(group, category)
```



```{r}

df_tab_hyp_fy2122 <- df_tab_fy2122 |>
  select(1:11)

gt_tab_hyp_fy2122 <- df_tab_hyp_fy2122 |>
  gt(
    rowname_col = "category",
    groupname_col = "group"
  ) |>
  row_group_order(groups = c("Population", "Sex", "Age band", "Ethnicity", "IMD", "Region", "Care home status", "Record or learning disability")) %>%
  tab_spanner(
    label = "HYP001 (Total population)",
    columns = c(hyp001_fy2122_numerator, hyp001_fy2122_denominator, hyp001_fy2122_pct)
  ) |>
  tab_spanner(
    label = "HYP003 (Age <= 79)",
    columns = c(hyp003_fy2122_numerator, hyp003_fy2122_denominator, hyp003_fy2122_pct)
  ) |>
  tab_spanner(
    label = "HYP007 (Age >= 80)",
    columns = c(hyp007_fy2122_numerator, hyp007_fy2122_denominator, hyp007_fy2122_pct)
  ) |>
  fmt_number(
    columns = c(
      hyp001_fy2122_numerator, hyp001_fy2122_denominator,
      hyp003_fy2122_numerator, hyp003_fy2122_denominator,
      hyp007_fy2122_numerator, hyp007_fy2122_denominator
    ),
    decimals = 0,
    use_seps = TRUE
  ) |>
  fmt_percent(
    columns = c(hyp001_fy2122_pct, hyp003_fy2122_pct, hyp007_fy2122_pct),
    decimals = 2,
    use_seps = TRUE
  ) |>
  cols_label(
    hyp001_fy2122_numerator = "Register",
    hyp001_fy2122_denominator = "List size",
    hyp001_fy2122_pct = "Prevalence",
    hyp003_fy2122_numerator = "Numerator",
    hyp003_fy2122_denominator = "Denominator",
    hyp003_fy2122_pct = md("Receiving<br>indicated care"),
    hyp007_fy2122_numerator = "Numerator",
    hyp007_fy2122_denominator = "Denominator",
    hyp007_fy2122_pct = md("Receiving<br>indicated care")
  ) |>
  tab_options(
    column_labels.font.size = "small",
    table.font.size = "small",
    row_group.font.size = "small",
    data_row.padding = px(2)
  ) |>
  text_transform(
    locations = cells_body(
      columns = c(
        hyp001_fy2122_numerator, hyp001_fy2122_denominator, hyp001_fy2122_pct,
        hyp003_fy2122_numerator, hyp003_fy2122_denominator, hyp003_fy2122_pct,
        hyp007_fy2122_numerator, hyp007_fy2122_denominator, hyp007_fy2122_pct
      )
    ),
    fn = function(x) {
      case_when(
        x == "NA" ~ "-",
        TRUE ~ x
      )
    }
  )

gt_tab_hyp_fy2122

gtsave(gt_tab_hyp_fy2122, here("released_outputs", "tables", "gt_tab_hyp_fy2122.png"))
```



```{r}

df_tab_bp_fy2122 <- df_tab_fy2122 |>
  select(1:2, 12:14)

df_tab_bp_fy2122 <- df_tab_bp_fy2122 |>
  drop_na()

df_tab_bp_fy2122 <- df_tab_bp_fy2122 |>
  mutate(category = case_when(
    category == "40-49" ~ "45-49",
    TRUE ~ category
  ))

gt_tab_bp_fy2122 <- df_tab_bp_fy2122 |>
  gt(
    rowname_col = "category",
    groupname_col = "group"
  ) |>
  row_group_order(groups = c("Population", "Sex", "Age band", "Ethnicity", "IMD", "Region", "Care home status", "Record or learning disability")) %>%
  tab_spanner(
    label = "BP002 (Age >= 45)",
    columns = c(bp002_fy2122_numerator, bp002_fy2122_denominator, bp002_fy2122_pct)
  ) |>
  fmt_number(
    columns = c(bp002_fy2122_numerator, bp002_fy2122_denominator),
    decimals = 0,
    use_seps = TRUE
  ) |>
  fmt_percent(
    columns = c(bp002_fy2122_pct),
    decimals = 2,
    use_seps = TRUE
  ) |>
  cols_label(
    bp002_fy2122_numerator = "Numerator",
    bp002_fy2122_denominator = "Denominator",
    bp002_fy2122_pct = md("Receiving<br>indicated care")
  ) |>
  tab_options(
    column_labels.font.size = "small",
    table.font.size = "small",
    row_group.font.size = "small",
    data_row.padding = px(2)
  ) |>
  text_transform(
    locations = cells_body(
      columns = c(bp002_fy2122_numerator, bp002_fy2122_denominator, bp002_fy2122_pct)
    ),
    fn = function(x) {
      case_when(
        x == "NA" ~ "-",
        TRUE ~ x
      )
    }
  )

gt_tab_bp_fy2122

gtsave(gt_tab_bp_fy2122, here("released_outputs", "tables", "gt_tab_bp_fy2122.png"))
```



```{r}

gt_tab_hyp_bp_fy2122 <- df_tab_fy2122 |>
  relocate(bp002_fy2122_numerator, bp002_fy2122_denominator, bp002_fy2122_pct, .after = category) |>
  gt(
    rowname_col = "category",
    groupname_col = "group"
  ) |>
  row_group_order(groups = c("Population", "Sex", "Age band", "Ethnicity", "IMD", "Region", "Care home status", "Record or learning disability")) %>%
  tab_spanner(
    label = "BP002 (Age >= 45)",
    columns = c(bp002_fy2122_numerator, bp002_fy2122_denominator, bp002_fy2122_pct)
  ) |>
  tab_spanner(
    label = "HYP001 (Total population)",
    columns = c(hyp001_fy2122_numerator, hyp001_fy2122_denominator, hyp001_fy2122_pct)
  ) |>
  tab_spanner(
    label = "HYP003 (Age <= 79)",
    columns = c(hyp003_fy2122_numerator, hyp003_fy2122_denominator, hyp003_fy2122_pct)
  ) |>
  tab_spanner(
    label = "HYP007 (Age >= 80)",
    columns = c(hyp007_fy2122_numerator, hyp007_fy2122_denominator, hyp007_fy2122_pct)
  ) |>
  fmt_number(
    columns = c(
      bp002_fy2122_numerator, bp002_fy2122_denominator,
      hyp001_fy2122_numerator, hyp001_fy2122_denominator,
      hyp003_fy2122_numerator, hyp003_fy2122_denominator,
      hyp007_fy2122_numerator, hyp007_fy2122_denominator
    ),
    decimals = 0,
    use_seps = TRUE
  ) |>
  fmt_percent(
    columns = c(bp002_fy2122_pct, hyp001_fy2122_pct, hyp003_fy2122_pct, hyp007_fy2122_pct),
    decimals = 2,
    use_seps = TRUE
  ) |>
  cols_label(
    bp002_fy2122_numerator = "Numerator",
    bp002_fy2122_denominator = "Denominator",
    bp002_fy2122_pct = md("Receiving<br>indicated care"),
    hyp001_fy2122_numerator = "Register",
    hyp001_fy2122_denominator = "List size",
    hyp001_fy2122_pct = "Prevalence",
    hyp003_fy2122_numerator = "Numerator",
    hyp003_fy2122_denominator = "Denominator",
    hyp003_fy2122_pct = md("Receiving<br>indicated care"),
    hyp007_fy2122_numerator = "Numerator",
    hyp007_fy2122_denominator = "Denominator",
    hyp007_fy2122_pct = md("Receiving<br>indicated care")
  ) |>
  tab_options(
    column_labels.font.size = "small",
    table.font.size = "small",
    row_group.font.size = "small",
    data_row.padding = px(2)
  ) |>
  text_transform(
    locations = cells_body(
      columns = c(
        bp002_fy2122_numerator, bp002_fy2122_denominator, bp002_fy2122_pct,
        hyp001_fy2122_numerator, hyp001_fy2122_denominator, hyp001_fy2122_pct,
        hyp003_fy2122_numerator, hyp003_fy2122_denominator, hyp003_fy2122_pct,
        hyp007_fy2122_numerator, hyp007_fy2122_denominator, hyp007_fy2122_pct
      )
    ),
    fn = function(x) {
      case_when(
        x == "NA" ~ "-",
        TRUE ~ x
      )
    }
  )

gtsave(gt_tab_hyp_bp_fy2122, here("released_outputs", "tables", "gt_tab_hyp_bp_fy2122.png"), expand = 10)
```
