This notebook creates the figures and tables for the manuscript.

# Load packages and function

```{r}

library(tidyverse)
library(lubridate)
library(here)
library(scales)
library(janitor)
library(patchwork)
library(gt)

```


```{r}

# Load plotting function
source(here::here("lib", "functions", "funs_plot_measures.R"))
source(here::here("lib", "functions", "funs_report_results.R"))

```

# Load data

```{r}

df_deciles_bp_hyp_practice <- read_csv(here("released_outputs/deciles/deciles_bp_hyp_practice.csv"))

df_deciles_bp_hyp_practice <- df_deciles_bp_hyp_practice |>
  mutate(percentile = factor(percentile,
                             levels = seq(10, 90, 10),
                             labels = c(seq(1, 4, 1), "5 - Median", seq(6, 9, 1))),
         indicator = factor(indicator, 
                            levels = c("hyp001", "hyp003", "hyp007", "bp002"),
                            labels = c("HYP001 (Total population)", "HYP003 (Age <= 79)", "HYP007 (Age >= 80)", "BP002 (Age >= 45)")))

df_deciles_bp_hyp_practice <- df_deciles_bp_hyp_practice |>
  filter(date < "2022-04-01") |>
  mutate(variable = "Practice level deciles")

df_deciles_bp_hyp_practice |>
  group_by(indicator) |>
  count()
```

```{r}

df_measures_bp_hyp <- read_csv(here("released_outputs/measures/df_measures_bp_hyp.csv")) |>
         mutate(indicator = factor(indicator, 
                                   levels = c("hyp001", "hyp003", "hyp007", "bp002"),
                                   labels = c("HYP001 (Total population)", "HYP003 (Age <= 79)", "HYP007 (Age >= 80)", "BP002 (Age >= 45)")))

# Start with end of FY
df_measures_bp_hyp <- df_measures_bp_hyp |>
  filter(date < "2022-04-01")

# Change age band group for BP002 so plot legends can be combined
df_plot_measures_bp_hyp <- df_measures_bp_hyp |>
  # mutate(category = case_when(indicator == "BP002 (Age >= 45)" & group == "age_band" & category == "45-49" ~ "40-49",
  #                             TRUE ~ category)) |>
  mutate(group = factor(group, levels = c("population", "sex", "age_band", "ethnicity", "imd_q5", "region", "care_home", "learning_disability"), 
                               labels = c("Population", "Sex", "Age band", "Ethnicity", "IMD", "Region", "Care home", "Learning disability")))


df_plot_measures_bp_hyp

```

## HYP001

```{r}

plot_hyp001_deciles_practice <- df_deciles_bp_hyp_practice |>
  filter(indicator %in% c("HYP001 (Total population)")) |>
  plot_qof_deciles(facet_wrap = TRUE,
                   facet_wrap_var = variable,
                   date_breaks = "3 months",
                   ylimits =  NULL,
                   ybreaks =  seq(0, 1, .02),
                   legend_position = "top",
                   legend_top_nrow = 1)

# plot_hyp001_deciles_practice

plot_hyp001_imd <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "IMD") |>
  filter(indicator %in% c("HYP001 (Total population)")) |>
  filter(category != "(Missing)") |>
  mutate(category = na_if(category, "missing")) |>
  plot_qof_values(legend_position = "top", 
                  date_breaks = "3 months",
                  legend_top_nrow = 1,
                  facet_wrap = TRUE,
                  facet_wrap_var = group)

# plot_hyp001_imd

plot_hyp001_age_band <- df_plot_measures_bp_hyp |>
    filter(variable == "pct") |>
    filter(group == "Age band") |>
    filter(indicator %in% c("HYP001 (Total population)")) |>
    plot_qof_values(legend_position = "top", 
                    legend_top_nrow = 2,
                    date_breaks = "3 months",
                    facet_wrap_var = group)

# plot_hyp001_age_band

plot_hyp001_eth <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Ethnicity") |>
  filter(indicator %in% c("HYP001 (Total population)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = group) +
  scale_colour_brewer(palette = "Set1")

# plot_hyp001_eth
  
plot_hyp001_region <- df_plot_measures_bp_hyp |>
    filter(variable == "pct")  |>
    filter(group == "Region") |>
    filter(indicator %in% c("HYP001 (Total population)")) |>
    drop_na(category) |>
    plot_qof_values(legend_position = "top", 
                    legend_top_nrow = 3,
                    date_breaks = "3 months",
                    facet_wrap_var = group) +
    scale_colour_manual(values = c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", 
                                   "#ff7f00",
                                   "#ffff33", "#a65628", "#f781bf", "#999999"))

# plot_hyp001_region

plot_hyp001_sex <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Sex") |>
  filter(indicator %in% c("HYP001 (Total population)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = group) +
  scale_colour_brewer(palette = "Dark2")

# plot_hyp001_sex

plot_hyp001_care_home <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Care home") |>
  filter(indicator %in% c("HYP001 (Total population)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = group) +
  scale_colour_brewer(palette = "Dark2")

# plot_hyp001_care_home

plot_hyp001_learning_disability <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Learning disability") |>
  filter(indicator %in% c("HYP001 (Total population)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = group) +
  scale_colour_brewer(palette = "Dark2")

# plot_hyp001_learning_disability
```

```{r}

plot_hyp001_breakdowns <- (plot_hyp001_deciles_practice + plot_hyp001_sex) /
  (plot_hyp001_age_band + plot_hyp001_region) /
  (plot_hyp001_eth + plot_hyp001_imd ) /
  (plot_hyp001_learning_disability + plot_hyp001_care_home) 

plot_hyp001_breakdowns <- plot_hyp001_breakdowns & ylab(NULL) & theme(legend.position = "top")

plot_hyp001_breakdowns <- plot_hyp001_breakdowns + plot_annotation(tag_levels = 'A')

plot_hyp001_breakdowns <- plot_hyp001_breakdowns & 
  theme_classic() &
  theme(legend.position = "bottom",
        text = element_text(size = 15),
        strip.background = element_rect(size = 0),
        strip.text.x = element_text(size = 13, face = "bold"))


ggsave(filename = here("released_outputs", "figures", "plot_hyp001_breakdowns.png"),
       plot = plot_hyp001_breakdowns,
       width = 12.8, 
       height = 15)

```


## HYP003

```{r}

plot_hyp003_deciles_practice <- df_deciles_bp_hyp_practice |>
  filter(indicator %in% c("HYP003 (Age <= 79)")) |>
  plot_qof_deciles(facet_wrap = TRUE,
                   facet_wrap_var = indicator,
                   date_breaks = "3 months",
                   ylimits =  NULL,
                   ybreaks =  seq(0, 1, .15),
                   legend_position = "top",
                   legend_top_nrow = 1)

# plot_hyp003_deciles_practice

plot_hyp003_imd <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "IMD") |>
  filter(indicator %in% c("HYP003 (Age <= 79)")) |>
  filter(category != "(Missing)") |>
  mutate(category = na_if(category, "missing")) |>
  plot_qof_values(legend_position = "top", 
                  date_breaks = "3 months",
                  legend_top_nrow = 1,
                  facet_wrap = TRUE,
                  facet_wrap_var = indicator)

# plot_hyp003_imd

plot_hyp003_age_band <- df_plot_measures_bp_hyp |>
    filter(variable == "pct") |>
    filter(group == "Age band") |>
    filter(indicator %in% c("HYP003 (Age <= 79)")) |>
    plot_qof_values(legend_position = "top", 
                    legend_top_nrow = 2,
                    date_breaks = "3 months",
                    facet_wrap_var = indicator)

# plot_hyp003_age_band

plot_hyp003_eth <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Ethnicity") |>
  filter(indicator %in% c("HYP003 (Age <= 79)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = indicator) +
  scale_colour_brewer(palette = "Set1")

# plot_hyp003_eth
  
plot_hyp003_region <- df_plot_measures_bp_hyp |>
    filter(variable == "pct")  |>
    filter(group == "Region") |>
    filter(indicator %in% c("HYP003 (Age <= 79)")) |>
    drop_na(category) |>
    plot_qof_values(legend_position = "top", 
                    legend_top_nrow = 2,
                    date_breaks = "3 months",
                    facet_wrap_var = indicator) +
    scale_colour_manual(values = c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", 
                                   "#ff7f00",
                                   "#ffff33", "#a65628", "#f781bf", "#999999"))

# plot_hyp003_region

plot_hyp003_sex <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Sex") |>
  filter(indicator %in% c("HYP003 (Age <= 79)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = indicator) +
  scale_colour_brewer(palette = "Dark2")

# plot_hyp003_sex

plot_hyp003_care_home <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Care home") |>
  filter(indicator %in% c("HYP003 (Age <= 79)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = indicator) +
  scale_colour_brewer(palette = "Dark2")

# plot_hyp003_care_home

plot_hyp003_learning_disability <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Learning disability") |>
  filter(indicator %in% c("HYP003 (Age <= 79)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = indicator) +
  scale_colour_brewer(palette = "Dark2")

# plot_hyp003_learning_disability
```

```{r}

plot_hyp003_breakdowns <- (plot_hyp003_deciles_practice + plot_hyp003_sex) /
  (plot_hyp003_age_band + plot_hyp003_region) /
  (plot_hyp003_eth + plot_hyp003_imd ) /
  (plot_hyp003_learning_disability + plot_hyp003_care_home) 

plot_hyp003_breakdowns <- plot_hyp003_breakdowns & ylab(NULL) & theme(legend.position = "top")

plot_hyp003_breakdowns <- plot_hyp003_breakdowns + plot_annotation(tag_levels = 'A')

plot_hyp003_breakdowns <- plot_hyp003_breakdowns & 
  theme_classic() &
  theme(legend.position = "bottom",
        text = element_text(size = 15),
        strip.background = element_rect(size = 0),
        strip.text.x = element_text(size = 13, face = "bold"))

plot_hyp003_breakdowns & scale_y_continuous(
          labels = scales::percent,
          limits = c(.3, .82)
        )

ggsave(filename = here("released_outputs", "figures", "plot_hyp003_breakdowns.png"),
       plot = plot_hyp003_breakdowns,
       width = 12.5, 
       height = 15)

```



## HYP007

```{r}

plot_hyp007_deciles_practice <- df_deciles_bp_hyp_practice |>
  filter(indicator %in% c("HYP007 (Age >= 80)")) |>
  plot_qof_deciles(facet_wrap = TRUE,
                   facet_wrap_var = indicator,
                   date_breaks = "3 months",
                   ylimits =  NULL,
                   ybreaks =  seq(0, 1, .15),
                   legend_position = "top",
                   legend_top_nrow = 1)

# plot_hyp007_deciles_practice

plot_hyp007_imd <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "IMD") |>
  filter(indicator %in% c("HYP007 (Age >= 80)")) |>
  filter(category != "(Missing)") |>
  mutate(category = na_if(category, "missing")) |>
  plot_qof_values(legend_position = "top", 
                  date_breaks = "3 months",
                  legend_top_nrow = 1,
                  facet_wrap = TRUE,
                  facet_wrap_var = indicator)

# plot_hyp007_imd

plot_hyp007_age_band <- df_plot_measures_bp_hyp |>
    filter(variable == "pct") |>
    filter(group == "Age band") |>
    filter(indicator %in% c("HYP007 (Age >= 80)")) |>
    plot_qof_values(legend_position = "top", 
                    legend_top_nrow = 2,
                    date_breaks = "3 months",
                    facet_wrap_var = indicator)

# plot_hyp007_age_band

plot_hyp007_eth <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Ethnicity") |>
  filter(indicator %in% c("HYP007 (Age >= 80)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = indicator) +
  scale_colour_brewer(palette = "Set1")

# plot_hyp007_eth
  
plot_hyp007_region <- df_plot_measures_bp_hyp |>
    filter(variable == "pct")  |>
    filter(group == "Region") |>
    filter(indicator %in% c("HYP007 (Age >= 80)")) |>
    drop_na(category) |>
    plot_qof_values(legend_position = "top", 
                    legend_top_nrow = 2,
                    date_breaks = "3 months",
                    facet_wrap_var = indicator) +
    scale_colour_manual(values = c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", 
                                   "#ff7f00",
                                   "#ffff33", "#a65628", "#f781bf", "#999999"))

# plot_hyp007_region

plot_hyp007_sex <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Sex") |>
  filter(indicator %in% c("HYP007 (Age >= 80)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = indicator) +
  scale_colour_brewer(palette = "Dark2")

# plot_hyp007_sex

plot_hyp007_care_home <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Care home") |>
  filter(indicator %in% c("HYP007 (Age >= 80)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = indicator) +
  scale_colour_brewer(palette = "Dark2")

# plot_hyp007_care_home

plot_hyp007_learning_disability <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Learning disability") |>
  filter(indicator %in% c("HYP007 (Age >= 80)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = indicator) +
  scale_colour_brewer(palette = "Dark2")

# plot_hyp007_learning_disability
```

```{r}

plot_hyp007_breakdowns <- (plot_hyp007_deciles_practice + plot_hyp007_sex) /
  (plot_hyp007_age_band + plot_hyp007_region) /
  (plot_hyp007_eth + plot_hyp007_imd ) /
  (plot_hyp007_learning_disability + plot_hyp007_care_home) 

plot_hyp007_breakdowns <- plot_hyp007_breakdowns & ylab(NULL) & theme(legend.position = "top")

plot_hyp007_breakdowns <- plot_hyp007_breakdowns + plot_annotation(tag_levels = 'A')

plot_hyp007_breakdowns <- plot_hyp007_breakdowns & 
  theme_classic() &
  theme(legend.position = "bottom",
        text = element_text(size = 15),
        strip.background = element_rect(size = 0),
        strip.text.x = element_text(size = 13, face = "bold"))

plot_hyp007_breakdowns & scale_y_continuous(
          labels = scales::percent,
          limits = c(.4, .92))

ggsave(filename = here("released_outputs", "figures", "plot_hyp007_breakdowns.png"),
       plot = plot_hyp007_breakdowns,
       width = 12.5, 
       height = 15)

```

## BP002

```{r}

plot_bp002_deciles_practice <- df_deciles_bp_hyp_practice |>
  filter(indicator %in% c("BP002 (Age >= 45)")) |>
  plot_qof_deciles(facet_wrap = TRUE,
                   facet_wrap_var = variable,
                   date_breaks = "3 months",
                   ylimits =  NULL,
                   ybreaks =  seq(0, 1, .04),
                   legend_position = "top",
                   legend_top_nrow = 1)

# plot_bp002_deciles_practice

plot_bp002_imd <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "IMD") |>
  filter(indicator %in% c("BP002 (Age >= 45)")) |>
  filter(category != "(Missing)") |>
  mutate(category = na_if(category, "missing")) |>
  plot_qof_values(legend_position = "top", 
                  date_breaks = "3 months",
                  legend_top_nrow = 1,
                  facet_wrap = TRUE,
                  facet_wrap_var = group)




# plot_bp002_imd

plot_bp002_age_band <- df_plot_measures_bp_hyp |>
    filter(variable == "pct") |>
    filter(group == "Age band") |>
    filter(indicator %in% c("BP002 (Age >= 45)")) |>
    plot_qof_values(legend_position = "top", 
                    legend_top_nrow = 2,
                    date_breaks = "3 months",
                    facet_wrap_var = group)

# plot_bp002_age_band

plot_bp002_eth <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Ethnicity") |>
  filter(indicator %in% c("BP002 (Age >= 45)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = group) +
  scale_colour_brewer(palette = "Set1")

# plot_bp002_eth

plot_bp002_region <- df_plot_measures_bp_hyp |>
    filter(variable == "pct")  |>
    filter(group == "Region") |>
    filter(indicator %in% c("BP002 (Age >= 45)")) |>
    drop_na(category) |>
    plot_qof_values(legend_position = "top", 
                    legend_top_nrow = 3,
                    date_breaks = "3 months",
                    facet_wrap_var = group) +
    scale_colour_manual(values = c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", 
                                   "#ff7f00",
                                   "#ffff33", "#a65628", "#f781bf", "#999999"))

# plot_bp002_region

plot_bp002_sex <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Sex") |>
  filter(indicator %in% c("BP002 (Age >= 45)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = group) +
  scale_colour_brewer(palette = "Dark2")

# plot_bp002_sex

plot_bp002_care_home <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Care home") |>
  filter(indicator %in% c("BP002 (Age >= 45)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = group) +
  scale_colour_brewer(palette = "Dark2")

# plot_bp002_care_home

plot_bp002_learning_disability <- df_plot_measures_bp_hyp |>
  filter(variable == "pct")  |>
  filter(group == "Learning disability") |>
  filter(indicator %in% c("BP002 (Age >= 45)")) |>
  plot_qof_values(legend_position = "top", 
                  legend_top_nrow = 1,
                  date_breaks = "3 months",
                  facet_wrap_var = group) +
  scale_colour_brewer(palette = "Dark2")

# plot_bp002_learning_disability
```



```{r}

plot_bp002_breakdowns <- ((plot_bp002_deciles_practice + plot_bp002_sex) & scale_y_continuous(labels = scales::percent, limits = c(.8, .95))) /
  (plot_bp002_age_band + plot_bp002_region) /
  (plot_bp002_eth + plot_bp002_imd ) /
  ((plot_bp002_learning_disability + plot_bp002_care_home) & scale_y_continuous(labels = scales::percent, limits = c(.8, 1))) 

plot_bp002_breakdowns <- plot_bp002_breakdowns & ylab(NULL) & theme(legend.position = "top")

plot_bp002_breakdowns <- plot_bp002_breakdowns + plot_annotation(tag_levels = 'A')

plot_bp002_breakdowns <- plot_bp002_breakdowns & 
  theme_classic() &
  theme(legend.position = "bottom",
        text = element_text(size = 15),
        strip.background = element_rect(size = 0),
        strip.text.x = element_text(size = 13, face = "bold"))

plot_bp002_breakdowns

ggsave(filename = here("released_outputs", "figures", "plot_bp002_breakdowns.png"),
       plot = plot_bp002_breakdowns,
       width = 12.5, 
       height = 15)

```



# Population

```{r}

plot_hyp001_population <- df_measures_bp_hyp |>
  filter(indicator == c("HYP001 (Total population)")) |>
  filter(variable == "pct")  |>
  filter(group == "population") |>
  filter(category != "missing") |>
  plot_qof_values(legend_position = "none", facet_wrap_ncol = 1) +
  scale_colour_viridis_d() +
  scale_y_continuous(labels = scales::label_percent(), limits = c(0, 1)) +
  scale_colour_manual(values = c("#440154FF", "#440154FF", "#440154FF", "#440154FF"))

# plot_hyp001_population

plot_hyp003_population <- df_measures_bp_hyp |>
  filter(indicator == "HYP003 (Age <= 79)") |>
  filter(variable == "pct")  |>
  filter(group == "population") |>
  filter(category != "missing") |>
  plot_qof_values(legend_position = "none", facet_wrap_ncol = 1,
                  ylab = "Patients receiving indicated care") +
  scale_colour_viridis_d() +
  scale_y_continuous(labels = scales::label_percent(), limits = c(0, 1)) +
  scale_colour_manual(values = c("#440154FF", "#440154FF", "#440154FF", "#440154FF"))

plot_hyp007_population <- df_measures_bp_hyp |>
  filter(indicator == "HYP007 (Age >= 80)") |>
  filter(variable == "pct")  |>
  filter(group == "population") |>
  filter(category != "missing") |>
  plot_qof_values(legend_position = "none", facet_wrap_ncol = 1,
                  ylab = "Patients receiving indicated care") +
  scale_colour_viridis_d() +
  scale_y_continuous(labels = scales::label_percent(), limits = c(0, 1)) +
  scale_colour_manual(values = c("#440154FF", "#440154FF", "#440154FF", "#440154FF"))

plot_bp002_population <- df_measures_bp_hyp |>
  filter(indicator == "BP002 (Age >= 45)") |>
  filter(variable == "pct")  |>
  filter(group == "population") |>
  filter(category != "missing") |>
  plot_qof_values(legend_position = "none", facet_wrap_ncol = 1,
                  ylab = "Patients receiving indicated care") +
  scale_colour_viridis_d() +
  scale_y_continuous(labels = scales::label_percent(), limits = c(0, 1)) +
  scale_colour_manual(values = c("#440154FF", "#440154FF", "#440154FF", "#440154FF"))

# plot_hyp003_hyp007_bp002_population

plot_reg_ind_population <- (plot_bp002_population + plot_hyp001_population) / (plot_hyp003_population + plot_hyp007_population) +  plot_annotation(tag_levels = 'A') & 
  theme_classic() &
  theme(legend.position = "none",
        text = element_text(size = 14),
        strip.background = element_rect(size = 0),
        strip.text.x = element_text(size = 13, face = "bold"))

plot_reg_ind_population

ggsave(filename = here("released_outputs", "figures", "plot_reg_ind_population.png"),
       plot = plot_reg_ind_population, width = 11, height = 7)

```
















```{r}

ggtheme_qof <- theme_classic() &
  theme(legend.position = "bottom",
        text = element_text(size = 15),
        strip.background = element_rect(size = 0),
        strip.text.x = element_text(size = 13, face = "bold"))

breakdown1_hyp003_hyp007 <- (plot_hyp003_deciles_practice + plot_hyp007_deciles_practice + plot_layout(guides = 'collect') & ggtheme_qof & scale_y_continuous(labels = scales::percent, limits = c(.29, .95))) /
  (plot_hyp003_sex + plot_hyp007_sex + plot_layout(guides = 'collect') & ggtheme_qof & scale_y_continuous(labels = scales::percent, limits = c(.4, .90))) /
  (plot_hyp003_age_band + plot_hyp007_age_band + plot_layout(guides = 'collect') & ggtheme_qof & scale_y_continuous(labels = scales::percent, limits = c(.4, .90))) /
  (plot_hyp003_eth + plot_hyp007_eth + plot_layout(guides = 'collect') & ggtheme_qof & scale_y_continuous(labels = scales::percent, limits = c(.4, .90)))

breakdown1_hyp003_hyp007 <- breakdown1_hyp003_hyp007 & ylab(NULL)
breakdown1_hyp003_hyp007 <- breakdown1_hyp003_hyp007 + plot_annotation(tag_levels = 'A')

ggsave(filename = here("released_outputs", "figures", "plot_breakdown1_hyp003_hyp007.png"),
       plot = breakdown1_hyp003_hyp007,
       width = 12.5, 
       height = 15)

breakdown2_hyp003_hyp007 <- (plot_hyp003_region + plot_hyp007_region + plot_layout(guides = 'collect') & ggtheme_qof & scale_y_continuous(labels = scales::percent, limits = c(.4, .90))) /
  (plot_hyp003_imd + plot_hyp007_imd + plot_layout(guides = 'collect') & ggtheme_qof & scale_y_continuous(labels = scales::percent, limits = c(.44, .88))) /
  (plot_hyp003_learning_disability + plot_hyp007_learning_disability + plot_layout(guides = 'collect') & ggtheme_qof & scale_y_continuous(labels = scales::percent, limits = c(.4, .90))) /
  (plot_hyp003_care_home + plot_hyp007_care_home + plot_layout(guides = 'collect') & ggtheme_qof & scale_y_continuous(labels = scales::percent, limits = c(.45, .90)))

breakdown2_hyp003_hyp007 <- breakdown2_hyp003_hyp007 & ylab(NULL)
breakdown2_hyp003_hyp007 <- breakdown2_hyp003_hyp007 + plot_annotation(tag_levels = 'A')


ggsave(filename = here("released_outputs", "figures", "breakdown2_hyp003_hyp007.png"),
       plot = breakdown2_hyp003_hyp007,
       width = 12.5, 
       height = 15)

```


```{r}


plot_hyp_management_counts <- df_plot_measures_bp_hyp |>
 mutate(variable = case_when(indicator == "HYP001 (Total population)" & variable == "register" ~ "numerator",
                             indicator == "HYP001 (Total population)" & variable == "population" ~ "denominator",
                             TRUE ~ variable)) |>
  filter(group == "Population") |>
  filter(indicator != "HYP001 (Total population)") |>
  filter(indicator != "BP002 (Age >= 45)") |>
  pivot_wider(names_from = "variable", values_from = "value") |>
  ggplot(aes(colour = numerator / denominator * 100)) +
  geom_segment(aes(x = date, 
                   xend = date, 
                   y = numerator, 
                   yend = denominator)) +
  scale_colour_viridis_c(name = "Patients receiving\nindicated care (%)", 
                         option = "mako", 
                         direction = -1, end = .8) +
  geom_point(aes(x = date, y = numerator), size = 2, shape = 15) +
  geom_point(aes(x = date, y = denominator), size = 2, shape = 16) +
  labs(x = NULL, y = "Count of patients") +
  scale_x_date(date_breaks = "4 month", labels = scales::label_date_short()) +
      theme(text = element_text(size = 14), 
            axis.text.x = element_text(size = 10),
            legend.position = "right") +
  facet_wrap(~indicator, scale = "free_y", ncol = 1) +
  ggplot2::scale_y_continuous(labels = scales::comma)

plot_bp_management_counts <- df_plot_measures_bp_hyp |>
 mutate(variable = case_when(indicator == "HYP001 (Total population)" & variable == "register" ~ "numerator",
                             indicator == "HYP001 (Total population)" & variable == "population" ~ "denominator",
                             TRUE ~ variable)) |>
  filter(group == "Population") |>
  # filter(indicator != "HYP001 (Total population)") |>
  filter(indicator == "BP002 (Age >= 45)") |>
  pivot_wider(names_from = "variable", values_from = "value") |>
  ggplot(aes(colour = numerator / denominator * 100)) +
  geom_segment(aes(x = date, 
                   xend = date, 
                   y = numerator, 
                   yend = denominator)) +
  scale_colour_viridis_c(name = "Patients receiving\nindicated care (%)", 
                         option = "mako", 
                         direction = -1, end = .8) +
  geom_point(aes(x = date, y = numerator), size = 2, shape = 15) +
  geom_point(aes(x = date, y = denominator), size = 2, shape = 16) +
  labs(x = NULL, y = "Count of patients") +
  scale_x_date(date_breaks = "4 month", labels = scales::label_date_short()) +
      theme(text = element_text(size = 14), 
            axis.text.x = element_text(size = 10),
            legend.position = "right") +
  facet_wrap(~indicator, scale = "free_y", ncol = 1) +
  ggplot2::scale_y_continuous(labels = scales::comma)

plot_hyp_records_counts <- df_plot_measures_bp_hyp |>
 mutate(variable = case_when(indicator == "HYP001 (Total population)" & variable == "register" ~ "numerator",
                             indicator == "HYP001 (Total population)" & variable == "population" ~ "denominator",
                             TRUE ~ variable)) |>
  filter(group == "Population") |>
  filter(indicator == "HYP001 (Total population)") |>
  pivot_wider(names_from = "variable", values_from = "value") |>
  ggplot(aes(colour = numerator / denominator * 100)) +
  geom_segment(aes(x = date, 
                   xend = date, 
                   y = numerator, 
                   yend = denominator)) +
  scale_colour_viridis_c(name = "Hypertension register (%)", 
                         option = "mako", 
                         direction = -1, end = .8) +
  geom_point(aes(x = date, y = numerator), size = 2, shape = 15) +
  geom_point(aes(x = date, y = denominator), size = 2, shape = 16) +
  labs(x = NULL, y = "Count of patients") +
  scale_x_date(date_breaks = "4 month", labels = scales::label_date_short()) +
      theme(text = element_text(size = 14), 
            axis.text.x = element_text(size = 10),
            legend.position = "right") +
  facet_wrap(~indicator, scale = "free_y", ncol = 1) +
  ggplot2::scale_y_continuous(labels = scales::comma)




library(patchwork)

plot_hyp_counts <- (plot_hyp_records_counts / plot_hyp_management_counts) &
  theme_classic() &
  theme(legend.position = "right",
        text = element_text(size = 14),
        strip.background = element_rect(size = 0),
        strip.text.x = element_text(size = 13, face = "bold")) &
  plot_layout(height = c(1, 2))

ggsave(filename = here("released_outputs", "figures", "plot_hyp_counts.png"),
       plot = plot_hyp_counts, width = 11, height = 7)

plot_bp_counts <- plot_bp_management_counts & 
  theme_classic() &
  theme(legend.position = "right",
        text = element_text(size = 14),
        strip.background = element_rect(size = 0),
        strip.text.x = element_text(size = 13, face = "bold"))

ggsave(filename = here("released_outputs", "figures", "plot_bp_counts.png"),
       plot = plot_bp_counts, width = 11, height = 7/3)


(plot_bp_management_counts / (plot_hyp_records_counts / plot_hyp_management_counts) &
  plot_layout(height = c(1, 2))) &
  # theme_classic() &
  theme(legend.position = "right",
        text = element_text(size = 14),
        # strip.background = element_rect(size = 0),
        strip.text.x = element_text(size = 13, face = "bold")) #&
  # plot_layout(height = c(1, 1))
```
